apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: aksclusters.azure.service.infrabox.net
spec:
  group: azure.service.infrabox.net
  names:
    kind: AKSCluster
    listKind: AKSClusterList
    plural: aksclusters
    singular: akscluster
  scope: Namespaced
  version: v1alpha1
